/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface JsChunkCoords {
  x: number
  z: number
}
export interface BlockInfo {
  stateId: number
  light: number
  skyLight: number
  biomeId: number
}
export type NapiWorld = World
export declare class World {
  constructor()
  loadColumn(chunkX: number, chunkZ: number, dataBuffer: Buffer): void
  unloadColumn(chunkX: number, chunkZ: number): void
  getBlockStateId(x: number, y: number, z: number): number
  setBlockStateId(x: number, y: number, z: number, stateId: number): void
  getBlock(x: number, y: number, z: number): BlockInfo | null
  getBlockLight(x: number, y: number, z: number): number
  getSkyLight(x: number, y: number, z: number): number
  getBiomeId(x: number, y: number, z: number): number
  exportSectionStates(chunkX: number, chunkZ: number, sectionY: number): Buffer | null
  getLoadedChunks(): { x: number; z: number; }[]
}
