/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface BlockInfo {
  stateId: number
  light: number
  skyLight: number
  biomeId: number
}
export type NapiWorld = World
export declare class World {
  constructor()
  /** Loads chunk column data from a network buffer (like `map_chunk` packet data). */
  loadColumn(chunkX: number, chunkZ: number, dataBuffer: Buffer): void
  /** Unloads a chunk column. */
  unloadColumn(chunkX: number, chunkZ: number): void
  /** Gets the state ID of the block at the given world coordinates. */
  getBlockStateId(x: number, y: number, z: number): number
  /** Sets the state ID of the block at the given world coordinates. */
  setBlockStateId(x: number, y: number, z: number, stateId: number): void
  /** Gets a simplified block object (stateId, light, skyLight, biomeId). */
  getBlock(x: number, y: number, z: number): BlockInfo | null
  /** Gets the block light level at the given world coordinates. */
  getBlockLight(x: number, y: number, z: number): number
  /** Gets the sky light level at the given world coordinates. */
  getSkyLight(x: number, y: number, z: number): number
  /** Gets the biome ID at the given world coordinates. */
  getBiomeId(x: number, y: number, z: number): number
}
